#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

build()
{
    distro=$1
    branch=$2
    machine=$3

    read -r -a array <<< "$distro $branch"
    base="$(IFS=-; echo "${array[*]+"${array[*]}"}")"

    read -r -a array <<< "$distro $branch $machine"
    tag="$(IFS=-; echo "${array[*]}")"

    docker build \
        --build-arg builder_base="anyakichi/yocto-builder:${base:-latest}" \
        --build-arg yocto_machine="${machine}" \
        -t "${DOCKER_REPO}:${tag}" \
        .
}

if [ $# -eq 0 ]; then
    for b in "" zeus warrior thud sumo rocko pyro morty krogoth jethro fido dizzy daisy; do
        for m in raspberrypi raspberrypi-cm raspberrypi-cm3 raspberrypi0 raspberrypi0-wifi raspberrypi2 raspberrypi3 raspberrypi3-64 raspberrypi4 raspberrypi4-64; do
            build ""      "${b}" "${m}"
            build bionic  "${b}" "${m}"
            build xenial  "${b}" "${m}"
            build trusty  "${b}" "${m}"
            build centos7 "${b}" "${m}"
        done
    done
else
    build "$@"
fi
