#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

push()
{
    distro=$1
    branch=$2
    machine=$3

    read -r -a array <<< "$distro $branch $machine"
    tag="$(IFS=-; echo "${array[*]}")"

    docker push "${DOCKER_REPO}:${tag}"
}

if [ $# -eq 0 ]; then
    for b in "" zeus warrior thud sumo rocko pyro morty krogoth jethro fido dizzy daisy; do
        for m in raspberrypi raspberrypi-cm raspberrypi-cm3 raspberrypi0 raspberrypi0-wifi raspberrypi2 raspberrypi3 raspberrypi3-64 raspberrypi4 raspberrypi4-64; do
            push ""      "${b}" "${m}"
            push bionic  "${b}" "${m}"
            push xenial  "${b}" "${m}"
            push trusty  "${b}" "${m}"
            push centos7 "${b}" "${m}"
        done
    done
else
    push "$@"
fi
